services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '.:/var/www/html'

    db:
      image: mysql:latest
      container_name: laravel_db
      restart: unless-stopped
      tty: true
      ports:
        - "3306:3306"
      environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: laravel
        MYSQL_PASSWORD: 'laravel'

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: laravel_phpmyadmin
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "8080:80"
